name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Add SSL certificat
      uses: DamianReeves/write-file-action@master
      with: 
        path: src/nginx/certificates/nginx.key
        write-mode: overwrite
        contents: ${{ secrets.NGINX_KEY }}
          
    - name: Add SSL certificat
      uses: DamianReeves/write-file-action@master
      with: 
        path: src/nginx/certificates/nginx-certificate.crt
        write-mode: overwrite
        contents: ${{ secrets.NGINX_CERTIFICATE_KEY }}

    - name: Send files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        source: src/
        target: bankroot

    - name: Build image and container to the server !
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/debian/bankroot/src/
          docker build -t angular/bankroot:v1 .
          docker-compose up -d
